import React from 'react';
import BannerWelcome from './_components/BannerWelcome';

export const metadata = {
  title: "Courses",
  description: "Generated by create next app",
};

function Courses() {
  return (
	<div className='grid md:grid-cols-3 p-5'>
    <div className='col-span-2'>
      <BannerWelcome />
    </div>
    <div className=''>
      Sidebar
    </div>

  </div>
  )
}

export default Courses