import React from 'react';

export const metadata = {
  title: "Courses",
  description: "Generated by create next app",
};

function Courses() {
  return (
	<div className='grid md:grid-cols-3'>
    <div className='col-span-2'>
      Banner
    </div>
    <div className=''>
      Sidebar
    </div>

  </div>
  )
}

export default Courses